# Финальная, самая надежная конфигурация v2

[build]
  # Команда сборки для корневого проекта нам больше не нужна.
  # publish и functions остаются прежними.
  publish = "public"
  functions = "netlify/functions"

# Эта новая секция - ключ к решению!
# Она говорит Netlify, что для папки с функциями нужно выполнить установку зависимостей.
[functions]
  # Эта строка указывает, что Netlify должен найти package.json внутри папки
  # netlify/functions и установить зависимости из него.
  node_bundler = "esbuild"
  external_node_modules = ["express", "jsonwebtoken", "serverless-http", "@netlify/blobs"]