# Финальная рабочая конфигурация

[build]
  # Эта команда установит все зависимости для функций
  command = "cd netlify/functions && npm install"
  
  # Папка, которую нужно опубликовать
  publish = "public" 
  
  # Папка, где лежат функции
  functions = "netlify/functions"

# Правила перенаправления для API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/news/:splat"
  status = 200

[[redirects]]
  from = "/admin-api/*"
  to = "/.netlify/functions/news-admin/:splat"
  status = 200

[[redirects]]
  from = "/admin/login"
  to = "/.netlify/functions/auth"
  status = 200
  force = true
  conditions = { "method" = ["POST"] }
[[redirects]]
from = "/admin/logout"
to = "/.netlify/functions/auth"
status = 200
force = true
[[redirects]]
from = "/admin/auth-check"
to = "/.netlify/functions/auth"
status = 200
force = true